name: Manual Build Docker Image

on:
  push:
    paths:
      - "ReleaseTag"
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”Checkout
        uses: actions/checkout@v2

      # Docker Image æ„å»ºç¯å¢ƒ
      - name: ğŸ—³ï¸Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: ğŸ¤–Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: âš“ Build and push
        uses: docker/build-push-action@v2
        with:
          tags: |
            imashen/pub-relay:master
