name: Manual Build Docker Image

on:
  push:
    paths:
      - "ReleaseTag"
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ”Checkout
        uses: actions/checkout@v2

      # Docker Image æ„å»ºç¯å¢ƒ
      - name: ğŸ—³ï¸Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: ğŸ—³ï¸Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: ğŸ¤–Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # è·å¾—ä»“åº“ä¸­çš„ReleaseTag
      - name: ğŸ—³ï¸Set Version
        id: set-version
        run: |
          echo "::set-output name=version::$(cat ReleaseTag | head -n1)"
          echo "ReleaseTag=$(cat ReleaseTag | head -n1)" 
          echo "::set-output name=status::success"
      # Build and push
      
      - name: ğŸ’•â¤ï¸Build and push
        if: steps.set-version.outputs.status == 'success'
        uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=imashen/pub-relay:dev
          cache-to: type=inline
          platforms: linux/amd64
          tags: |
            imashen/pub-relay:dev
            imashen/pub-relay:dev-${{steps.set-version.outputs.sha_short}}
